# Generated by Django 4.0.3 on 2022-04-20 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quests', '0002_alter_questions_date_posted_alter_questions_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='que',
        ),
    ]
